/**
 * The MedTech lifecycle model.
 *
 * These seven stages are the spine of the site: capability pages declare
 * which stages they touch, the homepage lifecycle explorer reads from here,
 * and the capability matrix is generated by intersecting stages with
 * capabilities. Adding a stage here propagates everywhere.
 */

export type LifecycleStageId =
  | "strategy"
  | "concept"
  | "develop"
  | "validate"
  | "industrialize"
  | "launch"
  | "scale"
  | "sustain";

export type LifecycleStage = {
  id: LifecycleStageId;
  label: string;
  /** One line, shown under the label in the explorer. */
  summary: string;
  /** What is actually happening in the business at this stage. */
  detail: string;
  /** Client-side questions that typically surface here. */
  questions: string[];
};

export const lifecycleStages: LifecycleStage[] = [
  {
    id: "strategy",
    label: "Strategy",
    summary: "Deciding what to build and why",
    detail:
      "The portfolio, the market, and the business case are still open questions. Decisions made here set the cost of everything downstream.",
    questions: [
      "Which opportunities justify investment?",
      "What does the competitive and regulatory landscape require?",
      "What is the realistic path to market?",
    ],
  },
  {
    id: "concept",
    label: "Concept",
    summary: "Establishing feasibility",
    detail:
      "Architecture options, early risk analysis, and user need definition. Cheap to change here, expensive everywhere after — and the stage most often compressed when a date is already committed.",
    questions: [
      "Have the user needs been stated precisely enough to design against?",
      "Which technical risks need retiring before committing to an architecture?",
      "Does the intended claim match the evidence we will be able to generate?",
    ],
  },
  {
    id: "develop",
    label: "Develop",
    summary: "Turning intent into a design",
    detail:
      "Requirements, architecture, and design work run in parallel with quality and regulatory planning. Coordination failures here surface much later as schedule loss.",
    questions: [
      "Are requirements stable enough to design against?",
      "Do design controls and development activity actually match?",
      "Who owns the cross-functional dependencies?",
    ],
  },
  {
    id: "validate",
    label: "Validate",
    summary: "Proving the design does what it claims",
    detail:
      "Verification, validation, human factors, and evidence generation converge. Rework discovered at this stage is expensive and highly visible.",
    questions: [
      "Is the V&V strategy aligned to the claims being made?",
      "Is the evidence package coherent across functions?",
      "What happens if a test fails late?",
    ],
  },
  {
    id: "industrialize",
    label: "Industrialize",
    summary: "Making it repeatably manufacturable",
    detail:
      "Design transfer, process validation, supplier readiness, and tooling. The point where engineering assumptions meet manufacturing reality.",
    questions: [
      "Is the design actually transferable as documented?",
      "Are suppliers qualified and capable at volume?",
      "Who is accountable when yield does not hold?",
    ],
  },
  {
    id: "launch",
    label: "Launch",
    summary: "Getting to market coherently",
    detail:
      "Regulatory clearance, commercial readiness, supply, training, and service all have to land at the same time. Launch is a coordination problem before it is a marketing one.",
    questions: [
      "Are regulatory, supply, and commercial timelines aligned?",
      "Is the field organization ready to support the product?",
      "What is the fallback if one workstream slips?",
    ],
  },
  {
    id: "scale",
    label: "Scale",
    summary: "Growing volume, markets, and footprint",
    detail:
      "Capacity, cost, new geographies, and additional configurations. The operating model that worked at launch often does not survive scale.",
    questions: [
      "Where does cost or capacity break first?",
      "What does entering the next market actually require?",
      "Is the supply base resilient enough?",
    ],
  },
  {
    id: "sustain",
    label: "Sustain",
    summary: "Keeping it performing in the field",
    detail:
      "Field issues, complaints, engineering changes, obsolescence, and continuous improvement — usually competing with new-product priorities for the same people.",
    questions: [
      "Who owns recurring field issues end to end?",
      "Is the change backlog under control?",
      "What happens when a critical component goes obsolete?",
    ],
  },
];

export const lifecycleStageMap: Record<LifecycleStageId, LifecycleStage> = Object.fromEntries(
  lifecycleStages.map((stage) => [stage.id, stage]),
) as Record<LifecycleStageId, LifecycleStage>;

export const lifecycleIntro = {
  eyebrow: "THE MEDTECH LIFECYCLE",
  heading: "Problems rarely stay inside one stage",
  copy: "A supplier issue found during industrialization is a design problem, a quality problem, and a launch problem at the same time. Stallion can engage at any stage — and, more usefully, across the seams between them.",
};
